# Generated by Django 4.2.25 on 2025-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_account_number_account_bank_name_account_bic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='account',
            name='iban',
        ),
        migrations.AddField(
            model_name='account',
            name='institution_number',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='transit_number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(default='Royal Bank of Canada', max_length=100),
        ),
    ]
