"""
Django settings for sphinx project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env early so env vars are available before configuring backends
ENV_PATH = BASE_DIR / ".env"
if ENV_PATH.exists():
    try:
        with open(ENV_PATH) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                os.environ.setdefault(key, value)
    except Exception:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-@2y$g6x$dmf#vlhir^9t-pwb)o7z1@6md(=ase#xwn__c!&zbw"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Read DEBUG from environment if provided
DEBUG = os.getenv("DEBUG", "1").lower() in ("1", "true", "yes")

# Hosts allowed when DEBUG=False (comma-separated in env). Defaults for local dev.
ALLOWED_HOSTS_STR = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost")
ALLOWED_HOSTS = [
    h.strip()
    for h in ALLOWED_HOSTS_STR.split(",")
    if h.strip()
]

# In production, also add the domain if not in ALLOWED_HOSTS
if not DEBUG and ALLOWED_HOSTS_STR:
    # Add common variations
    for host in ALLOWED_HOSTS[:]:  # Copy list to avoid modification during iteration
        if host and '.' in host:
            # Add domain without www if www is present
            if host.startswith('www.'):
                ALLOWED_HOSTS.append(host[4:])
            # Add www version if not present
            elif not any(h.startswith('www.' + host) for h in ALLOWED_HOSTS):
                ALLOWED_HOSTS.append('www.' + host)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.humanize",
    "accounts",
    "transactions",
    "notifications",
    "support",
    "profiles",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "accounts.middleware.OTPRequiredMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Must be last for static files
]

ROOT_URLCONF = "sphinx.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sphinx.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use PostgreSQL if DATABASE_URL is set (for production), otherwise SQLite (for local dev)
try:
    import dj_database_url
    DATABASE_URL = os.getenv("DATABASE_URL")
    if DATABASE_URL:
        DATABASES = {
            "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
except ImportError:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "America/Toronto"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# WhiteNoise configuration for production
# In production (DEBUG=False), WhiteNoise serves files from STATIC_ROOT
# In development, use finders for auto-reload
WHITENOISE_USE_FINDERS = DEBUG  # Use finders only in development
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh only in development
WHITENOISE_ROOT = STATIC_ROOT  # Root for static files
WHITENOISE_INDEX_FILE = False

# WhiteNoise cache configuration for admin static files
WHITENOISE_MANIFEST_STRICT = False  # Don't fail if manifest entry missing
# Skip already compressed files - Don't serve index files
WHITENOISE_SKIP_COMPRESSED_EXTENSIONS = [
    'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz',
    'xz', 'br'
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Default to filebased emails so messages are inspectable if SMTP isn't set
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "tmp" / "emails"
try:
    os.makedirs(EMAIL_FILE_PATH, exist_ok=True)
except Exception:
    pass
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "support@royal.local")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "[ROYAL] ")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))

# Optional SMTP configuration via environment variables
# If EMAIL_HOST is set and not empty, switch to SMTP backend
EMAIL_HOST_ENV = os.getenv("EMAIL_HOST", "").strip()
EMAIL_HOST_USER_ENV = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD_ENV = os.getenv("EMAIL_HOST_PASSWORD", "").strip()

if EMAIL_HOST_ENV and EMAIL_HOST_USER_ENV and EMAIL_HOST_PASSWORD_ENV:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = EMAIL_HOST_ENV
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = EMAIL_HOST_USER_ENV
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD_ENV
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "1") == "1"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "0") == "1"
    EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))
    # Log SMTP configuration (without password)
    logger = logging.getLogger(__name__)
    logger.info(
        f"✓ SMTP configuré: {EMAIL_HOST}:{EMAIL_PORT}, "
        f"utilisateur: {EMAIL_HOST_USER}, TLS: {EMAIL_USE_TLS}, "
        f"SSL: {EMAIL_USE_SSL}"
    )
    logger.info(f"✓ DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")
else:
    # Log that file-based backend is being used with details
    logger = logging.getLogger(__name__)
    missing = []
    if not EMAIL_HOST_ENV:
        missing.append("EMAIL_HOST")
    if not EMAIL_HOST_USER_ENV:
        missing.append("EMAIL_HOST_USER")
    if not EMAIL_HOST_PASSWORD_ENV:
        missing.append("EMAIL_HOST_PASSWORD")
    logger.warning(f"⚠️  Variables SMTP manquantes: {', '.join(missing)}")
    user_preview = (
        f"{EMAIL_HOST_USER_ENV[:3]}..." if EMAIL_HOST_USER_ENV
        else "non défini"
    )
    password_status = '***' if EMAIL_HOST_PASSWORD_ENV else 'non défini'
    logger.warning(
        f"⚠️  EMAIL_HOST='{EMAIL_HOST_ENV or 'non défini'}', "
        f"EMAIL_HOST_USER='{user_preview}', "
        f"EMAIL_HOST_PASSWORD={password_status}"
    )
    logger.warning(
        f"⚠️  Les emails seront sauvegardés dans {EMAIL_FILE_PATH} "
        f"au lieu d'être envoyés par SMTP"
    )
    logger.warning(
        "⚠️  Configurez toutes les variables EMAIL_HOST, "
        "EMAIL_HOST_USER et EMAIL_HOST_PASSWORD dans Render Dashboard"
    )
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"


SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")

# Logging configuration for production
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.request': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
        },
    }

# Security headers for admin pages to prevent cache issues
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# WhiteNoise configuration to ensure admin static files are served correctly
# Add max-age cache headers for static files but allow revalidation
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0  # 1 year in production, no cache in dev

# Disable immutable file test for admin - ensures admin static files are always served
def whitenoise_immutable_file_test(path, url):
    """Always return False to allow revalidation of admin static files"""
    return False

WHITENOISE_IMMUTABLE_FILE_TEST = whitenoise_immutable_file_test

# Trust the Render proxy for HTTPS so Django génère des URLs correctes et
# reconnaît le schéma HTTPS derrière le proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF trusted origins: requis en prod pour les POST/formulaires depuis le domaine custom
# On génère à partir des ALLOWED_HOSTS (hors wildcards) avec schéma https
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if host and not host.startswith("*")
]

# Cookies sécurisés en production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
